### ISSUE TITLE
String cannot be empty

### ISSUE THREAD

**Issue by jpann** [StefH/GitHubReleaseNotes#16]
GitHubReleaseNotes (1.0.6.0)

I get this error when trying to use this on my repo.

```
GitHubReleaseNotes (1.0.6.0)
...
Getting Issues and Pull Requests from 'git@github.com:jpann/SSRSMigrate.git'
String cannot be empty
Parameter name: owner
```

**Comment by jpann** [comment]
Looks like it is related to this [line](https://github.com/StefH/GitHubReleaseNotes/blob/7873e251aa33923176eeef9fabd8cd5ece356025/src/GitHubReleaseNotes.Logic/RepositoryHelper.cs#L175) since the url being passed to that method is in the SSH format 'git@github.com:OWNER/PROJECTNAME.git' and not in the expected 'HTTPS' format that the regex is expecting.

**Comment by StefH** [comment]
Hello @jpann, you are correct. I never tested this with the SSH format.

I never used SSH to clone a project.

I'll take a look at the regex, but maybe you can also help me on this?

**Comment by StefH** [comment]
@jpann Thanks for creating the issue + PR.

A new version (1.0.7) will be uploaded to Chocolatey, winget and NuGet today.
