### ISSUE TITLE
Group issues by label

### ISSUE THREAD

**Issue by Rick-van-Dam** [StefH/GitHubReleaseNotes#6]
It would be nice if the release notes could be grouped by a label. It would look a bit like this:

# 1.0.4.16 (11 September 2018)

## Features
 - [#202](https://github.com/StefH/GitHubReleaseNotes/pull/202) - Update logic PR contributed by [StefH](https://github.com/StefH)

## Bugfixes
 - [#201](https://github.com/StefH/GitHubReleaseNotes/issues/201) - Fix issue abc

The labels of the PR could be used to do this. Though we would have to find a way to deal with multiple labels on a single PR. Maybe the end user can define a mapping between labels and what eventually gets in the release notes. To prevent duplicate entries we could prioritize some above others. So if a PR has both a `bug` and `feature` label the `bug` label would be used.

**Comment by StefH** [comment]
It's possible to get the Labels from an issue or pr.
A simpler approach could be to just get the labels and add these to the issue / pr (only add when defined).

Like
```
#202 - Update logic PR [feature] contributed by StefH
#201 - Fix issue abc [bug, question]
#999 - Fix issue xyz
```

**Comment by StefH** [comment]
linked to https://github.com/StefH/GitHubReleaseNotes/pull/7
